-- DropIndex
DROP INDEX "Analysis_propertyId_key";

-- AlterTable
ALTER TABLE "Analysis" ADD COLUMN     "afaRate" DOUBLE PRECISION NOT NULL DEFAULT 0.02,
ADD COLUMN     "buildingShare" DOUBLE PRECISION NOT NULL DEFAULT 0.80,
ADD COLUMN     "cashflowAfterTax" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "closingCosts" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "closingCostsRate" DOUBLE PRECISION NOT NULL DEFAULT 0.10,
ADD COLUMN     "equity" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "equityRatio" DOUBLE PRECISION NOT NULL DEFAULT 0.20,
ADD COLUMN     "loan" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "loanInterestRate" DOUBLE PRECISION NOT NULL DEFAULT 0.038,
ADD COLUMN     "loanRepaymentRate" DOUBLE PRECISION NOT NULL DEFAULT 0.02,
ADD COLUMN     "maintenanceRate" DOUBLE PRECISION NOT NULL DEFAULT 0.30,
ADD COLUMN     "monthlyAfA" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "monthlyInterest" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "monthlyMaintenance" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "monthlyRepayment" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "monthlyVacancyLoss" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "netYield" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "scenarioName" TEXT NOT NULL DEFAULT 'Standard',
ADD COLUMN     "taxRateIncome" DOUBLE PRECISION NOT NULL DEFAULT 0.42,
ADD COLUMN     "totalInvestment" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "vacancyRate" DOUBLE PRECISION NOT NULL DEFAULT 0.05,
ALTER COLUMN "grossYield" SET DEFAULT 0,
ALTER COLUMN "cashflow" SET DEFAULT 0,
ALTER COLUMN "score" SET DEFAULT 0;
